baseurl = "https://furdikisherpa.github.io./hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
languageCode = "en-us"
title = "Gyan Jyoti High School"
themesDir = "themes"
theme = "hugo-universal-theme"

[submodule]
  path = path_to_submodule 
  url = https://github.com/Furdikisherpa/Schoolsite.git

[menu]

#Home (main menu)

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1




#About us (main menu)

[[menu.main]]
    name       = "About Us"
    identifier = "menu.portfolio"
    url        = "/img/carousel/template-mac.jpg"
    weight     = 2


#About Us (Sub menu)

[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = ""
    weight     = 1
    parent     = "menu.portfolio"
    post       = 1

[[menu.main]]
    name       = "Mission & Vision"
    url        = "/about/mission/"
    weight     = 1
    parent     = "section.about"

[[menu.main]]
    name       = "Administrative Staff and Faculty Member"
    url        = "/about/staff/"
    weight     = 2
    parent     = "section.about"
    
[[menu.main]]
    name       = "School History"
    url        = "/about/history/"
    weight     = 3
    parent     = "section.about"

[[menu.main]]
    name       = "Hours Of Operation"
    url        = "/about/hours/"
    weight     = 4
    parent     = "section.about"    
    
[[menu.main]]
    name       = "Contact Us"
    url        = "/contact/"
    weight     = 5
    parent     = "section.about"
    

#Academics (main menu)

[[menu.main]]
    name       = "Academics"
    identifier = "menu.academics"
    url        = "/img/carousel/template-easy-code.jpg"
    weight     = 3
    
[[menu.main]]
    name       = "Academics"
    identifier = "section.academics"
    url        = ""
    weight     = 1
    parent     = "menu.academics"
    post       = 1

[[menu.main]]
    name       = "ELementary School"
    url        = "/academics/elementary"
    weight     = 1
    parent     = "section.academics"

[[menu.main]]
    name       = "Middle School"
    url        = "/academics/middle"
    weight     = 2
    parent     = "section.academics"

[[menu.main]]
    name       = "High School"
    url        = "/academics/high"
    weight     = 3
    parent     = "section.academics"

[[menu.main]]
    name       = "Art, Athletics & Activities"
    url        = "/academics/arts"
    weight     = 4
    parent     = "section.academics"

#Services (main menu)

[[menu.main]]
    name       = "Facilities"
    identifier = "menu.allpages"
    url        = "/img/carousel/template-easy-customize.jpg"
    weight     = 3


[[menu.main]]
    name       = "Services"
    identifier = "section.ap-home"
    url        = "/home/"
    weight     = 1
    parent     = "menu.allpages"
    post       = 1

[[menu.main]]
    name       = "Food & Nutrition"
    url        = "/services/food/"
    weight     = 1
    parent     = "section.ap-home"    

[[menu.main]]
    name       = "Transportation Services"
    url        = "/services/transport/"
    weight     = 2
    parent     = "section.ap-home"
    
[[menu.main]]
    name       = "Health Services"
    url        = "/services/health/"
    weight     = 2
    parent     = "section.ap-home"          
#Admission (main menu)

[[menu.main]]
    name       = "Admissions"
    identifier = "menu.Admission"
    weight     = 4
    url	       ="/admission/"
    post       = 4  
  
  #Blogs (main menu)

[[menu.main]]
    name       = "News & Events"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5
    post       = 5
    
#Services (main menu)

[[menu.main]]
    name       = "Career"
    identifier = "menu.career"
    weight     = 6
    url	       ="/career/"
    post       = 6    
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:gyanjyoti12@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = """<p>MISSION & VISION
    		<br>ADMINISTRATIVE STAFF & FACULTY MEMBER
    		<br>SCHOOL HISTORY
    		<br>HOURS OF OPERATION
    		<br>CONTACT US</p>"""
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "GYAN JYOTI HIGH SCHOOL"

    logo = "img/W(1).png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase">Saraswotinagar, Kathmandu Nepal
        <br><br><strong>Phone No.:</strong> 977 9867402724
        <br><br><strong>Email Id :</strong> gyanjyoti12@gmail.com.
        <br><br><strong>Website :</strong> gyanjyotihighschool.com.np
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +977 9867402724 or gyanjyoti12@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:gyanjyoti12@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have taught with many students and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our students said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Current Vacancies"
    subtitle = "“Work to become, not to acquire.” – Elbert Hubbard."
    link_url = "/career/"
    link_text = "CAREER"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "GYAN JYOTI HIGH SCHOOL"
    subtitle = "Gyan jyoti high school is a multicultural community in the foothills of the Himalaya that inspires in each student a passion for learning, the confidence and competence to pursue their dreams, and the commitment to serve as a compassionate global citizen and leader, who is a steward of the environment."


	
[params.recent_posts]
    enable = true
    title = "From our blog"
    #subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
